version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "angularjs",
    "meteor",
    "ember"
  ]
  environment = [
    "jquery",
    "nodejs",
    "browser",
    "mongo",
    "jest",
    "cypress",
    "mocha",
    "vitest",
    "jasmine"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "google-java-format"